### PR TITLE
Add gdb and time to runtime container

### PR DESCRIPTION
**Pull request by cmarkello**

### CODE REVIEW

**Comment by cmarkello** [comment]
@glennhickey @adamnovak ready for review

**Comment by glennhickey** [comment]
This PR doesn't make much sense to me.  Why add gdb to our "-run" image that doesn't even include any source?  Even #5 which added it to the full image seems like overkill, when, unless I'm missing something, it can be installed as needed in an interactive session.

**Comment by cmarkello** [comment]
@glennhickey @adamnovak 
I'm trying to install packages for the purposes of debugging `std::bad_alloc` errors that I've been running into when attempting to run the xg index. That bad_alloc error in the xg indexing program appears to occur in vg containers after version `v1.5.0-824-gcc531354-t73-run` (I'm double checking this right now). I've been stuck on this error for a while now.

`gdb` and `time` can't be installed as needed since `apt-get` isn't installed in the container. I've tried this before.
Adam recommended that I install gdb and time for debugging purposes in the runtime container.

**Comment by glennhickey** [comment]
Is there a reason you can't use the -build images for debugging?  apt-get works fine in them, though gdb's been built in since #5....

`docker run -it quay.io/vgteam/vg:v1.5.0-1674-g8b3f26a8-t108-build`

**Comment by adamnovak** [comment]
apt-get doesn't work in the containers *on singularity*, because the kernel
doesn't tell apt in the container that it is root.

I guess you could just use the build containers and not the run containers
for debugging. The entry points on the build containers aren't set like
they are on the run containers, so it can't be a drop-in replacement. But
since you start up the container manually for debugging anyway, it might
work fine.

**Comment by glennhickey** [comment]
I see for apt-get.  

toil-vg doesn't care about entry points, so the build images should work equivalently to the run images.  In any case, they will be more useful for debugging via singularity shell.

**Pull request closed without merging**
